### ISSUE TITLE
Allow changing the initial live point likelihood for PolyChord dead-birth output?

### ISSUE THREAD

**Issue by thjsal** [ejhigson/nestcheck#10]
Hello,

When combining multiple MultiNest runs (in https://github.com/xpsi-group/xpsi/blob/main/xpsi/PostProcessing/_runs.py), we first write the output files in PolyChord format using the `write_run_output()` function of nestcheck and then later process the runs using other nestcheck functions.  However, sometimes we end up with AssertionErrors like 
```
AssertionError: [-9.96891777e+89 -9.96350959e+89 -9.95151606e+89 ... -1.01012441e+89
 -1.00664888e+89 -1.00651256e+89]
```
which I think may be caused by some of the samples in the usual sample files having a worse likelihood than those in the dead-birth files. The solution in our case has been to change (https://github.com/ejhigson/nestcheck/blob/27aadb2164d6e9eb0734f35f4bb18eec07f4f544/nestcheck/write_polychord_output.py#L148):
```
if th['thread_min_max'][0, 0] == -np.inf:
    samp_arr[0, ndim + 1] = -1e30
```
to 
```
if th['thread_min_max'][0, 0] == -np.inf:
    samp_arr[0, ndim + 1] = -0.179769313486231571E+309
```
where the latter number corresponds to the initial live point likelihood for MultiNest runs mentioned here: https://github.com/ejhigson/nestcheck/blob/master/nestcheck/data_processing.py. 

Could it be possible to allow users to set this number as a keyword argument, or are there other suggestions? I can make a pull request if the idea is ok.

**Comment by ejhigson** [comment]
Hi @thjsal - thank you for pointing this out. A keyword argument that defaults to the old behavior sounds like a safe change. Yes please go ahead and send a pull request, and make sure all the tests pass.

Many thanks,
Ed
