### ISSUE TITLE
Error when processing polychord stats

### ISSUE THREAD

**Issue by tilmantroester** [ejhigson/nestcheck#2]
dyPolychord (using the `master` version of polychord) crashed on me with the error 
```
File "/home/ttroester/Codes/miniconda/envs/kcap/lib/python3.7/site-packages/nestcheck/data_processing.py", line 407, in process_polychord_stats
    output['avnlikeslice'] = float(lines[25 + nclust].split()[3])
ValueError: could not convert string to float: '('
Error in process with rank == 0: forcing MPI abort.
```

The offending stats file is (the only one around)
```
Evidence estimates:
===================
  - The evidence Z is a log-normally distributed, with location and scale parameters mu and sigma.
  - We denote this as log(Z) = mu +/- sigma.

Global evidence:
----------------

log(Z)       =  -0.658104755164217E+005 +/-   0.734163810568805E+000


Local evidences:
----------------

log(Z_ 1)  =  -0.658104755164217E+005 +/-   0.734163810568805E+000


Run-time information:
---------------------

 ncluster:          0 /       1
 nposterior:        0
 nequals:           0
 ndead:             5
 nlive:             0
 nlike:            43     137
 <nlike>:        0.00    0.00   (    0.00    0.00 per slice )
```
The 4th element of the last line is indeed `(`, which is probably not what nestcheck wants. I don't know enough about the polychord stats file format to come up with a fix though.

**Comment by williamjameshandley** [comment]
Pretty sure it's a PolyChord fast-slow parameter issue, and was addressed in this PC issue:
https://github.com/PolyChord/PolyChordLite/issues/20
Do you have the latest version of PolyChord?

**Comment by tilmantroester** [comment]
Indeed, that seems to be the case. The fix for polychord hasn't been implemented in nestcheck, however. I'll do that and make a PR.

**Comment by ejhigson** [comment]
Thank you @tilmantroester and @williamjameshandley!

**Comment by ejhigson** [comment]
@tilmantroester thank you for #3 - I have now merged it, as well as doing some additional tidying and fixing the tests. Let me know if everything works ok for you with the latest commit b76022c51f7b69b0a88dad078752de2b5c766bdb and if so I will close the issue.

**Comment by ejhigson** [comment]
I'm now closing this issue - let me know if there are any problems and I can reopen it.
