### ISSUE TITLE
reading multinest files

### ISSUE THREAD

**Issue by andrewfowlie** [ejhigson/nestcheck#5]
I'm surprised this hasn't come up before, so maybe I am mistaken. It seems to be that MutliNest writes files with the name [root]dead-birth.txt, i.e., with no dash added. So unless I choose a root that ends in a dash, I can't read the files as the reader assumes a dash:

https://github.com/ejhigson/nestcheck/blob/f9341a4f8dd533c701ab2a340cd4ac4c0bd79798/nestcheck/data_processing.py#L283-L286
 
Very easy fix if so.

**Comment by ejhigson** [comment]
Hi @andrewfowlie - thank you for pointing this out! I'm afraid I have not used MultiNest in many years so I am not familiar with the file naming conventions, but if you would be willing to submit a pull request to improve this filename format code then I'm happy to review/merge it?

Many thanks,
Ed

**Comment by ejhigson** [comment]
Thank you for the PR! I'll close this issue now, let me know/reopen if any issues.
