### ISSUE TITLE
nestcheck failing with dynamic sampling using dynesty

### ISSUE THREAD

**Issue by ekerrison** [ejhigson/nestcheck#8]
Hello,

I've found that when running nestcheck on the output from Dynesty it fails when using dynamic nested sampling with the error (filenames truncated for brevity):

```
Traceback (most recent call last):
  File "/.../dynesty.py", line 373, in nestcheck_data
  ns_run = nestcheck.data_processing.process_dynesty_run(out_file)
  File "/.../nestcheck/data_processing.py", line 365, in process_dynesty_run
  File "/.../nestcheck/ns_run_utils.py", line 125, in dict_given_run_array
AssertionError: nlive contains 0s or negative values. nlive_0=512
nlive_array = [  512.   512.   512. ... -1021. -1022. -1023.]
```

It looks to me like this is happening because the `nlive_array` is initialised based on the number of live points in the first batch, and doesn't take into account the additional points added in subsequent batches (in the example above I had 2 x 512 point batches in my Dynesty run).

I'm running Dynesty through Bilby as a wrapper, but I don't _think_ that makes any difference to the output I get, as my sampler output still contains all the parameters listed in the Dynesty documentation.

(Edit:) For reference I'm using dynesty v2.1.2, in case that's useful :)

**Comment by ekerrison** [comment]
Hi, me again,

I think I've found a potential fix? Dynamic runs from Dynesty out put a `results.samples_n` array that tracks the number of live samples with every iteration. This could be used directly in the `process_dynesty_run()` function to address the error above if it is incorporated into the `samples` array in that function

**Comment by ejhigson** [comment]
Hi @ekerrison - thank you very much for raising this ticket! I'm afraid I have left academia and am no longer familiar with dynesty. If you have the time then please could you make a pull request which implements the solution you suggested? Then assuming the tests pass I'll merge it for you.

Best wishes,
Ed

**Comment by ekerrison** [comment]
Hi Ed,

No problem! I'll make a pull request with the suggested solution

Best,
Emily
